//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace proiect_baze_de_date
{
    using System;
    using System.Collections.Generic;
    
    public partial class COMANDA_STOC
    {
        public decimal COMANDA_STOC_ID { get; set; }
        public Nullable<System.DateTime> DATA_PLASARE { get; set; }
        public Nullable<System.DateTime> DATA_LIVRARE { get; set; }
        public Nullable<int> CANTITATE { get; set; }
        public short CONTRACT_ID { get; set; }
    
        public virtual CONTRACT CONTRACT { get; set; }
    }
}
