//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace proiect_baze_de_date
{
    using System;
    using System.Collections.Generic;
    
    public partial class CONTRACT
    {
        public CONTRACT()
        {
            this.COMANDA_STOC = new HashSet<COMANDA_STOC>();
        }
    
        public short CONTRACT_ID { get; set; }
        public Nullable<System.DateTime> DATA_CONTRACT { get; set; }
        public Nullable<int> PRET { get; set; }
        public short FURNIZOR_ID { get; set; }
        public short PRODUSE_ID { get; set; }
    
        public virtual ICollection<COMANDA_STOC> COMANDA_STOC { get; set; }
        public virtual FURNIZOR FURNIZOR { get; set; }
        public virtual PRODUSE PRODUSE { get; set; }
    }
}
