//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace proiect_baze_de_date
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRODUCATOR
    {
        public PRODUCATOR()
        {
            this.PRODUSEs = new HashSet<PRODUSE>();
        }
    
        public short PRODUCATOR_ID { get; set; }
        public string NUME_PRODUCATOR { get; set; }
        public string WEBSITE { get; set; }
        public Nullable<int> TELEFON { get; set; }
    
        public virtual ICollection<PRODUSE> PRODUSEs { get; set; }
    }
}
