//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace proiect_baze_de_date
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRODUSE
    {
        public PRODUSE()
        {
            this.CONTRACTs = new HashSet<CONTRACT>();
        }
    
        public short PRODUS_ID { get; set; }
        public string NUME_PRODUS { get; set; }
        public string MODEL_PRODUS { get; set; }
        public Nullable<int> PRET { get; set; }
        public short PRODUCATOR_ID { get; set; }
        public short CATEGORIE_SPORT_ID { get; set; }
    
        public virtual CATEGORIE_SPORT CATEGORIE_SPORT { get; set; }
        public virtual ICollection<CONTRACT> CONTRACTs { get; set; }
        public virtual PRODUCATOR PRODUCATOR { get; set; }
    }
}
